Contact form collaboration
eerapheal/my-Portfolio pull request #2
Opened 2022-07-06 16:13 UTC by eerapheal

Contact form completed.

2022-07-07 05:50 UTC, muneebulrehman requested changes
Hi @eerapheal , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 05:50 UTC, muneebulrehman commented on index.html
> +      <div class="line4"></div>
Consider adding some margin between the heading and the form as in the figma design. Also, consider removing the outline when the name and email inputs fields are in focus.
Here is the reference of your app.
![image](https://user-images.githubusercontent.com/33268927/177700968-c2691016-ac61-41c4-938d-1af340c3f18e.png)

2022-07-07 15:46 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Ralph,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  💯🌟 

## Highlights 👍
- Form validation properly implemented
- Form action and method properly implemented


<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 09:34 UTC, eerapheal commented
Thanks for the review.

2022-07-08 09:35 UTC, merged