Desktop version
eerapheal/my-Portfolio pull request #7
Opened 2022-07-13 20:17 UTC by eerapheal

Complete desktop version.

2022-07-13 22:34 UTC, ShahierNashaat requested changes
Hi @eerapheal , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 22:34 UTC, ShahierNashaat commented on index.html
> +      </div>
- [ ] Kindly be noticed that you should follow the Figma design in your portfolio.
- [ ] Please in the desktop size make the font bigger, add the background image, make the icons of the nav bar to the right, and make the icons for Twitter, Linkedin, etc a little bit up.
- [ ] Also in the mobile size make the nav bar as the Figma design.

Your Design | Figma Design
---------------- | --------------------
![Screenshot from 2022-07-14 00-06-57](https://user-images.githubusercontent.com/33752735/178846638-9d8b7d43-4335-41c7-8edd-864c998b8e41.png) | ![Screenshot from 2022-07-14 00-06-31](https://user-images.githubusercontent.com/33752735/178846660-c685f2fa-d3de-4441-9643-ead765d6a45c.png)

Your Design | Figma Design
---------------- | --------------------
![Screenshot from 2022-07-14 00-11-59](https://user-images.githubusercontent.com/33752735/178846758-f861a775-fa87-4cd2-a618-bd9f6d640855.png) | ![Screenshot from 2022-07-14 00-11-33](https://user-images.githubusercontent.com/33752735/178846807-c36237c9-389b-4dc8-aeea-4d7fcd9709dd.png)

2022-07-13 22:34 UTC, ShahierNashaat commented on index.html
>        </div>
- [ ] Kindly be noticed that should follow the Figma design in your portfolio.
- [ ] Please put the first project in the center as it is at the left of the page.
- [ ] Also please make the div that holds each other projects bigger than the Figma design.
- [ ] Also in the mobile size make the see project button width the same as the width of the div that holds the project.

Your Design | Figma Design
---------------- | ------------------
![Screenshot from 2022-07-14 00-08-11](https://user-images.githubusercontent.com/33752735/178847454-b0e768a9-2620-452b-9c09-59d755c8fa92.png) | ![Screenshot from 2022-07-14 00-07-45](https://user-images.githubusercontent.com/33752735/178847477-6104ced2-7cae-4783-8d7e-216391eeb905.png)

Your Design | Figma Design
---------------- | ------------------
![Screenshot from 2022-07-14 00-08-52](https://user-images.githubusercontent.com/33752735/178847624-ae4afae5-96b5-4c75-847b-a8fbae9d96de.png) | ![Screenshot from 2022-07-14 00-08-33](https://user-images.githubusercontent.com/33752735/178847664-062c54bd-a36e-4330-bc11-26196bf5348c.png)

Your Design | Figma Design
---------------- | ------------------
![Screenshot from 2022-07-14 00-12-38](https://user-images.githubusercontent.com/33752735/178847728-41132534-fd83-46fb-b284-a8f85337d7c8.png) | ![Screenshot from 2022-07-14 00-12-26](https://user-images.githubusercontent.com/33752735/178847747-94d0f0a0-c512-48b9-b0df-61ddf66db56d.png)

2022-07-13 22:34 UTC, ShahierNashaat commented on index.html
>            <button class="sec-3-div-btn" type="button">Get My Resume</button>
- [ ] Kindly be noticed that you should follow the Figma design in your portfolio.
- [ ] Kindly make the background image of the about me section in the mobile size a little bit down.
- [ ] Also make the `Get My Resume` button a the left of the page.

Your Design | Figma Design
---------------- | --------------------
![Screenshot from 2022-07-14 00-13-22](https://user-images.githubusercontent.com/33752735/178848089-bba44edc-b8e4-44b3-9715-1e67f53646b5.png) | ![Screenshot from 2022-07-14 00-13-05](https://user-images.githubusercontent.com/33752735/178848109-491f39a2-3f3f-4e78-88e8-497ad44a9544.png)

2022-07-13 22:34 UTC, ShahierNashaat commented on index.html
>              <div class="line3"></div>
- [ ] Kindly be noticed that you should follow the Figma design in your portfolio.
- [ ] Please delete the extra space between the form and the footer.

Your Design | Figma Design
---------------- | --------------------
![Screenshot from 2022-07-14 00-09-58](https://user-images.githubusercontent.com/33752735/178848418-3f13d5ae-923e-4e48-a0f9-451b930310f8.png) | ![Screenshot from 2022-07-14 00-09-41](https://user-images.githubusercontent.com/33752735/178848433-d406e32f-e992-4e78-ac73-bff35db41ea8.png)

2022-07-14 12:39 UTC, ishimwezachee requested changes
Hi @eerapheal , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/JSpOjm7hBzMvyNYElU/giphy.gif"/>

## Highlights


## Required Changes ♻️

- [ ]  I can see you've done some changes, but again you still miss important part of the project as previous reviewer suggested. 
Please refer to the figma design, and impliment all the changes requested by the reviewer. 

Your design 
![image](https://user-images.githubusercontent.com/43877689/178983566-fe8b5ac2-94df-4764-8431-cba4d2397eb7.png)

Figma design 
![image](https://user-images.githubusercontent.com/43877689/178984112-380a9a13-08ca-4fb1-a46a-1bfa9039999d.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 18:57 UTC, omarsalem7 requested changes
Hi @eerapheal, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive pull request title

 ## Required Changes ♻️

- [ ] Kindly make the changes as stated by the previous reviewer and make your design match the Figma design by giving appropriate padding and margin.

| Your design  | Figma design|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/53402600/179061221-b99c8258-6e54-4bf9-b76b-5c3d6fa6d9b5.png)  | ![image](https://user-images.githubusercontent.com/43877689/178984112-380a9a13-08ca-4fb1-a46a-1bfa9039999d.png) |


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 21:30 UTC, vickymarz requested changes
Hi @eerapheal, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that has some failing linter checks. Kindly fix the linter errors and submit again. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-16 22:26 UTC, vickymarz requested changes
Hi @eerapheal , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

 You have submitted a project, that has some failing linter checks. Kindly fix the linter errors and submit again.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-16 22:33 UTC, eerapheal commented
There is no linters message at my end.

On Sun, 17 Jul 2022 at 06:26, Okoroji Victor Ebube ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @eerapheal <https://github.com/eerapheal> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> ❌ Invalid Code Review Request
>
> You have submitted a project, that has some failing linter checks. Kindly
> fix the linter errors and submit again.
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eerapheal/my-Portfolio/pull/7#pullrequestreview-1041032173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYCSBZHFCKVYUBBNTK47IK3VUMZKFANCNFSM53P6DBRQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-17 00:46 UTC, mwanawabangona approved these changes
Hi @eerapheal ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-17 00:46 UTC, mwanawabangona commented on index.html
> -      <div>
- [ ] `optional`
- [ ] please add the background image on the desktop version. please see screenshots below

`figma template`
![Screenshot from 2022-07-17 02-38-44](https://user-images.githubusercontent.com/66230306/179379305-70ea2d34-8873-4100-9d74-09ed54938930.png)

`your template`
![Screenshot from 2022-07-17 02-38-14](https://user-images.githubusercontent.com/66230306/179379321-f2a63e48-2b1f-4b5d-a7e7-c5c7f0e0ed90.png)

2022-07-18 13:30 UTC, merged

2022-07-18 13:30 UTC, eerapheal commented
I really appreciate your comments